description: |-
  Active Directory Investigation playbook provides tools and guidance to investigate changes and manipulation in Active Directory containers, ACLs, Schema, and objects.
  This playbook uses a 3rd party tool provided by Microsoft to scan the Active Directory access list, trees, and objects.
  Additional investigative information is provided for manual investigation.
id: Active Directory Investigation
inputs: []
name: Active Directory Investigation
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1e402223-77fd-4729-898d-51d541d65526
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 1e402223-77fd-4729-898d-51d541d65526
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -110
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "AdminSDHolder - \n\n1. AdminSDHolder is a container that exists\
        \ in every Active Directory domain for a particular purpose. \nThe Access\
        \ Control List (ACL) of the AdminSDHolder object is used as a template to\
        \ copy permissions to all “protected groups” in Active Directory and their\
        \ members. \nProtected groups include privileged groups such as Domain Admins,\
        \ Administrators, Enterprise Admins, and Schema Admins. \nThis includes other\
        \ groups that give logon rights to domain controllers, which can be enough\
        \ access to perpetrate attacks to compromise the domain.\n\n\n2. Active Directory\
        \ will take the ACL of the AdminSDHolder object and apply it to all protected\
        \ users and groups periodically to make sure the access to these objects is\
        \ secure. This works, in theory, because the default ACL for AdminSDHolder\
        \ is very restrictive. \nHowever, if an attacker can manipulate the ACL for\
        \ AdminSDHolder, those permissions will automatically be applied to all protected\
        \ objects. \nThis will give an attacker a way to create persistent access\
        \ to privileged accounts within the domain.\n\n\n3. The AdminSDHolder permissions\
        \ are pushed down to all protected objects by a process SDProp. By default,\
        \ this happens every 60 minutes, but this interval can be changed by modifying\
        \ a registry key value. \nThat means if an administrator sees inappropriate\
        \ permission on a protected object and removes it, within an hour, those permissions\
        \ will be put back in place by SDProp.\n\n\n4. More information about AdminSDHolder\
        \ -\nhttps://docs.microsoft.com/en-us/previous-versions/technet-magazine/ee361593(v=msdn.10)?redirectedfrom=MSDN#id0250006\n\
        \n\n5. Review Permissions for the AdminSDHolder container. You can do so by\
        \ right-clicking it, properties,  security, advanced, and review permissions\
        \ entries for unwanted users/groups.\n"
      id: ea482bb2-97ea-417d-815b-3d4cff43e48a
      iscommand: false
      name: Active Directory AdminSDHolder
      type: regular
      version: -1
    taskid: ea482bb2-97ea-417d-815b-3d4cff43e48a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 20
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "This step's goal is to quickly determine the affected accounts\
        \ that the attacker was able to compromise. \nAttackers will aim for a high\
        \ privileged domain account that will enable them to spread and deliver a\
        \ malicious payload to the largest volume of endpoint/servers. \n\nTo simplify\
        \ the work of creating and documenting the delegation model in Active Directory,\
        \ here is a tool in PowerShell with a GUI.\nThis tool creates reports of the\
        \ access control list for all of your Active Directory objects. With these\
        \ reports, you can see what/where, and when permissions have been set.\n\n\
        To run the script, you need at least PowerShell 2.0 and Windows 7/Windows\
        \ Server 2008 (Windows Server 2003 with Limited functionality).\n\nEnabled\
        \ unsigned scripting:\nSet-ExecutionPolicy Unrestricted\n\nIf you are not\
        \ a local admin and cannot set it on your machine, you can set it for your\
        \ profile:\nSet-ExecutionPolicy Unrestricted -Scope CurrentUser\nYou do not\
        \ need Powershell Module for Active Directory.\n\nMicrosoft article about\
        \ Active Directory forensics with ACL Scanner:\nhttps://docs.microsoft.com/en-us/archive/blogs/pfesweplat/forensics-active-directory-acl-investigation\n\
        \nMicrosoft article about AD ACL scanner tool:\nhttps://docs.microsoft.com/en-us/archive/blogs/pfesweplat/take-control-over-ad-permissions-and-the-ad-acl-scanner-tool\n\
        \nAD ACL Scanner Github project:\nhttps://github.com/canix1/ADACLScanner\n"
      id: 63dc8892-db0a-46d4-8dc6-1517a4033576
      iscommand: false
      name: Active Directory ACL Scanner
      type: regular
      version: -1
    taskid: 63dc8892-db0a-46d4-8dc6-1517a4033576
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
  "3":
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: "List the compromised users. \nCan be in CSV Format."
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      sender: ""
      title: List compromised users
      totalanswers: 0
    id: "3"
    ignoreworker: false
    message:
      bcc:
      body:
        simple: List compromised users
      cc:
      format: ""
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Review and Document ADL Scanner results in the incident.\n "
      id: 5dbb4398-13fb-4ccd-89af-a0e21515ea39
      iscommand: false
      name: Review ACL Scanner report
      type: collection
      version: -1
    taskid: 5dbb4398-13fb-4ccd-89af-a0e21515ea39
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: "0"
                root: List compromised users.Answers
          operator: isNotEmpty
      label: "yes"
    id: "4"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 75fb198a-a1c0-4aec-82d5-ba490633a3c7
      iscommand: false
      name: Did a compromised account detected?
      type: condition
      version: -1
    taskid: 75fb198a-a1c0-4aec-82d5-ba490633a3c7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Baseline domain controller events to log in to examine: \n(If\
        \ ACL Scanner returned positive results, search for more events around the\
        \ time and date of the results)\n\n4794 DSRM account password change attempt\
        \ - If this isn’t expected, could be malicious\n4780 ACLs set on admin accounts\
        \ - If this isn’t expected, could be malicious\n4739/643 Domain Policy was\
        \ changed - If this isn’t expected, could be malicious\n4713/617 Kerberos\
        \ policy was changed - If this isn’t expected, could be malicious\n4724/628\
        \ Attempt to reset an account’s password - Monitor for admin & sensitive account\
        \ PW reset\n4735/639 Security-enabled local group changed- Monitor admin/sensitive\
        \ group membership changes\n4737/641 Security-enabled global group changed\
        \ -Monitor admin/sensitive group membership changes\n4755/659 Security-enabled\
        \ universal group changed - Monitor admin & sensitive group membership"
      id: d53edd91-8322-4777-8584-45626a1c1681
      iscommand: false
      name: Active Directory event log
      type: regular
      version: -1
    taskid: d53edd91-8322-4777-8584-45626a1c1681
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1170
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c6bfd504-a4b5-4359-8574-8be3eacd17e1
      iscommand: false
      name: Remediate according to Event log findings.
      type: regular
      version: -1
    taskid: c6bfd504-a4b5-4359-8574-8be3eacd17e1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1330
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 385f5cda-bfd6-4a47-8ff3-b3feb3b0d68c
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 385f5cda-bfd6-4a47-8ff3-b3feb3b0d68c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1490
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      base-dn: {}
      username:
        complex:
          accessor: users
          root: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Disables an Active Directory user account.
      id: 99a12b85-ffca-4a11-8c6f-229811ac2a22
      iscommand: true
      name: Disable compromised account in Active Directory
      script: '|||ad-disable-account'
      type: regular
      version: -1
    taskid: 99a12b85-ffca-4a11-8c6f-229811ac2a22
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 990
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      accountid: {}
      accountname: {}
      addLabels: {}
      agentid: {}
      app: {}
      appendMultiSelect: {}
      assetid: {}
      assigneduser: {}
      assignmentgroup: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      blockedaction: {}
      bugtraq: {}
      caller: {}
      city: {}
      closeNotes: {}
      closeReason: {}
      cloudservice: {}
      commandline: {}
      costcenter: {}
      costcentercode: {}
      country: {}
      countryname: {}
      criticalassets: {}
      customFields: {}
      cve: {}
      cvss: {}
      dbotMirrorDirection: {}
      dbotMirrorId: {}
      dbotMirrorInstance: {}
      dbotMirrorTags: {}
      dbotprediction: {}
      dbotpredictionprobability: {}
      dbottextsuggestionhighlighted: {}
      deleteEmptyField: {}
      department: {}
      dest: {}
      desthostname: {}
      destinationhostname: {}
      destinationip: {}
      destinationnetwork: {}
      destinationport: {}
      destntdomain: {}
      destos: {}
      details: {}
      detectedexternalhosts: {}
      detectedexternalips: {}
      detectedinternalhosts: {}
      detectedinternalips: {}
      detectedusers: {}
      detectionendtime: {}
      detectionid: {}
      detectionupdatetime: {}
      detectionurl: {}
      deviceexternalip: {}
      devicehash: {}
      devicelocalip: {}
      devicemodel: {}
      devicename: {}
      displayname: {}
      duration: {}
      email: {}
      emailauthenticitycheck: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclassification: {}
      emailclientname: {}
      emailfrom: {}
      emailheaders: {}
      emailhtml: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      employeedisplayname: {}
      employeeemail: {}
      employeemanageremail: {}
      escalation: {}
      eventaction: {}
      eventid: {}
      eventtype: {}
      externaladdresses: {}
      filehash: {}
      filename: {}
      filepath: {}
      filesize: {}
      firstname: {}
      firstseen: {}
      givenname: {}
      helloworldid: {}
      helloworldstatus: {}
      helloworldtype: {}
      hostname: {}
      hosts: {}
      id: {}
      incomingmirrorerror: {}
      infectedhosts: {}
      internaladdresses: {}
      investigationstage: {}
      isolated: {}
      jobcode: {}
      jobfamily: {}
      jobfunction: {}
      labels: {}
      lastmodifiedby: {}
      lastmodifiedon: {}
      lastname: {}
      lastseen: {}
      leadership: {}
      location: {}
      locationregion: {}
      logsource: {}
      macaddress: {}
      maliciousbehavior: {}
      malwarefamily: {}
      malwarename: {}
      manageremailaddress: {}
      managername: {}
      md5: {}
      mobiledevicemodel: {}
      mobilephone: {}
      name: {}
      occurred: {}
      os: {}
      osversion: {}
      outgoingmirrorerror: {}
      owner: {}
      parentprocessid: {}
      personalemail: {}
      phase: {}
      phishingsubtype: {}
      phonenumber: {}
      pid: {}
      policydeleted: {}
      policydescription: {}
      policydetails: {}
      policyid: {}
      policyrecommendation: {}
      policyremediable: {}
      policyseverity: {}
      policytype: {}
      protocol: {}
      protocols: {}
      quarantined: {}
      ransomwareapproximatenumberofencryptedendpoints: {}
      ransomwarecryptocurrencyaddress: {}
      ransomwarecryptocurrencyaddresstype: {}
      ransomwaredataencryptionstatus: {}
      ransomwareemail: {}
      ransomwareencryptedfileowner: {}
      ransomwarenote: {}
      ransomwareonionurl: {}
      ransomwarerecoverytool: {}
      ransomwarestrain: {}
      rating: {}
      region: {}
      regionid: {}
      replacePlaybook: {}
      reporteremailaddress: {}
      resourceid: {}
      resourcename: {}
      resourcetype: {}
      riskrating: {}
      riskscore: {}
      roles: {}
      samaccountname: {}
      severity: {}
      sha256: {}
      signature: {}
      skuname: {}
      skutier: {}
      sla: {}
      slaField: {}
      sourcehostname: {}
      sourceip: {}
      sourcenetwork: {}
      sourceport: {}
      sourceusername: {}
      src: {}
      srchostname: {}
      srcntdomain: {}
      srcos: {}
      srcuser: {}
      state: {}
      streetaddress: {}
      subcategory: {}
      subtype: {}
      surname: {}
      systems: {}
      tenantname: {}
      terminatedaction: {}
      threatactor: {}
      ticketcloseddate: {}
      ticketnumber: {}
      ticketopeneddate: {}
      title: {}
      triggeredsecurityprofile: {}
      type: {}
      uniqueports: {}
      urlsslverification: {}
      user: {}
      useraccountcontrol: {}
      username: {}
      users:
        complex:
          accessor: "0"
          root: List compromised users.Answers
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
      workphone: {}
      zipcode: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: f0e2dcb1-88f6-440e-892c-9c70c931c6b3
      iscommand: true
      name: 'Set Compromised users '
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: f0e2dcb1-88f6-440e-892c-9c70c931c6b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 830
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "4_6_#default#": 0.16
    },
    "paper": {
      "dimensions": {
        "height": 1665,
        "width": 380,
        "x": 450,
        "y": -110
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
