id: 91e56c2a-257c-4a50-8430-a0cf09b29168
version: 53
name: Get File Sample From Path - Generic V2
description: |
  This playbook returns a file sample correlating to a path into the war-room using the following sub-playbooks:
  inputs:
  1) Get File Sample From Path - D2.
  2) Get File Sample From Path - VMware Carbon Black EDR (Live Response API).
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5d887731-fb71-4226-872c-a9e8dbddac42
    type: start
    task:
      id: 5d887731-fb71-4226-872c-a9e8dbddac42
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 8adb1ff3-5400-4f88-8a2b-4511ae8303f5
    type: condition
    task:
      id: 8adb1ff3-5400-4f88-8a2b-4511ae8303f5
      version: -1
      name: Use D2 agent?
      description: Yes if we want to use D2 agent to get the file
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "10"
    scriptarguments:
      left:
        simple: ${inputs.UseD2}
      right:
        simple: "True"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.UseD2
            iscontext: true
          right:
            value:
              simple: "yes"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: f81d6908-8ce9-452b-8dde-689f44256933
    type: title
    task:
      id: f81d6908-8ce9-452b-8dde-689f44256933
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 0245733c-b0c2-418e-8d68-a58a2c7ffe1a
    type: playbook
    task:
      id: 0245733c-b0c2-418e-8d68-a58a2c7ffe1a
      version: -1
      name: Get File Sample From Path - D2
      description: |-
        Returns a file sample to the war-room from a path on an endpoint using Demisto Dissolvable Agent (D2)

        Input:
        * Credentials - credentials to use when trying to deploy Demisto Dissolvable Agent (D2)  (default: Admin)
        * ${Endpoint.Hostname} - deploy agent on target endpoint
        * ${File.Path} - file's path to collect
      playbookName: Get File Sample From Path - D2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Credentials:
        simple: Admin
      Hostname:
        simple: ${Endpoint.Hostname}
      Path:
        simple: ${File.Path}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 1,
          "y": 355
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "11":
    id: "11"
    taskid: 906138a1-e3ee-4711-889a-4ebcc8c2a1c6
    type: title
    task:
      id: 906138a1-e3ee-4711-889a-4ebcc8c2a1c6
      version: -1
      name: Use VMware Carbon Black EDR (Live Response API)
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 931591d2-1338-45bf-8083-0a91db928068
    type: playbook
    task:
      id: 931591d2-1338-45bf-8083-0a91db928068
      version: -1
      name: Get File Sample From Path - VMware Carbon Black EDR (Live Response API)
      playbookName: Get File Sample From Path - VMware Carbon Black EDR - Live Response
        API
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Path:
        complex:
          root: inputs.Path
      Sensor_ID:
        complex:
          root: inputs.Sensor_ID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 480,
          "y": 510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 705,
        "width": 859,
        "x": 1,
        "y": 50
      }
    }
  }
inputs:
- key: UseD2
  value: {}
  required: false
  description: |-
    Determines whether a D2 agent will be used to retrieve the file.
    Default is no.
  playbookInputQuery: null
- key: Hostname
  value: {}
  required: false
  description: Hostname of the machine on which the file is located.
  playbookInputQuery: null
- key: Path
  value: {}
  required: false
  description: File path.
  playbookInputQuery: null
- key: Sensor_ID
  value: {}
  required: false
  description: Carbon Black sensor ID. Provided the sensor ID to run the command with
    a new session. The session will be created and closed automatically.
  playbookInputQuery: null
outputs:
- contextPath: File
  description: The file to sample.
  type: unknown
- contextPath: CbLiveResponse.File.Size
  description: File size.
- contextPath: CbLiveResponse.File.SHA1
  description: File SHA1.
- contextPath: CbLiveResponse.File.SHA256
  description: File SHA256.
- contextPath: CbLiveResponse.File.Name
  description: File name.
- contextPath: CbLiveResponse.File.SSDeep
  description: File SSDeep.
- contextPath: CbLiveResponse.File.EntryID
  description: File EntryID.
- contextPath: CbLiveResponse.File.Info
  description: File info.
- contextPath: CbLiveResponse.File.Type
  description: File type.
- contextPath: CbLiveResponse.File.MD5
  description: File MD5.
- contextPath: CbLiveResponse.File.Extension
  description: File extension.
sourceplaybookid: get_file_sample_from_path_-_generic
