id: 8a655839-e51f-465f-81e3-12185ac0484f
version: 35
name: Get File Sample By Hash - Generic v3
description: |-
  This playbook returns a file sample correlating to a hash in the war-room using the following sub-playbooks:
  - Get binary file by MD5 hash from Carbon Black telemetry data. - VMware Carbon Black EDR v2.
  - Get the threat (file) attached to a specific SHA256 hash- Cylance Protect v2.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e1c3bf5a-d7ba-4062-8877-ad2799d1db03
    type: start
    task:
      id: e1c3bf5a-d7ba-4062-8877-ad2799d1db03
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: b5e5705d-8e32-41bb-8c3b-63c78bd2d14f
    type: title
    task:
      id: b5e5705d-8e32-41bb-8c3b-63c78bd2d14f
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a88a3bd6-0201-4203-8e8b-b3962ed19718
    type: playbook
    task:
      id: a88a3bd6-0201-4203-8e8b-b3962ed19718
      version: -1
      name: Get File Sample By Hash - Cylance Protect v2
      description: This playbook returns a file sample to the war-room given the file's
        SHA256 hash, using Cylance Protect v2 integration.
      playbookName: Get File Sample By Hash - Cylance Protect v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      SHA256:
        simple: ${inputs.SHA256}
      unzip: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 490,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "6":
    id: "6"
    taskid: ae94bf0f-480b-4cc7-8cb1-d44313763369
    type: playbook
    task:
      id: ae94bf0f-480b-4cc7-8cb1-d44313763369
      version: -1
      name: Get binary file from Carbon Black by MD5 hash
      description: 'This playbook retrieve binary file by MD5 hash from Carbon Black
        telemetry data.   '
      playbookName: Get binary file from Carbon Black by MD5 hash
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      MD5:
        complex:
          root: inputs.MD5
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 35,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 835,
        "x": 35,
        "y": 50
      }
    }
  }
inputs:
- key: MD5
  value: {}
  required: false
  description: Get file sample from MD5 input
  playbookInputQuery: null
- key: SHA256
  value: {}
  required: false
  description: Get file sample from SHA256 input
  playbookInputQuery: null
outputs:
- contextPath: File
  description: File sample object
  type: unknown
sourceplaybookid: Get File Sample By Hash - Generic v2
