id: Retrieve File from Endpoint - Generic V2
version: -1
name: Retrieve File from Endpoint - Generic V2
description: |-
  This playbook retrieves a file sample from an endpoint using the following playbooks:
  - Get File Sample From Path - Generic v2.
  - Get File Sample By Hash - Generic v3.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: aafd2bad-97ae-4462-85cb-8ef1cad54fc5
    type: start
    task:
      id: aafd2bad-97ae-4462-85cb-8ef1cad54fc5
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 21df4e3f-565e-48ca-8937-7106ed312e6e
    type: title
    task:
      id: 21df4e3f-565e-48ca-8937-7106ed312e6e
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 912761f3-e299-4ff5-86f2-33e81bb75178
    type: playbook
    task:
      id: 912761f3-e299-4ff5-86f2-33e81bb75178
      version: -1
      name: Get File Sample By Hash - Generic v3
      description: |-
        This playbook returns a file sample correlating to a hash in the war-room using the following sub-playbooks:
        - Get binary file by MD5 hash from Carbon Black telemetry data. - VMware Carbon Black EDR v2.
        - Get the threat (file) attached to a specific SHA256 hash- Cylance Protect v2.
      playbookName: Get File Sample By Hash - Generic v3
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      MD5:
        complex:
          root: inputs.MD5
      SHA256:
        complex:
          root: inputs.SHA256
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 505,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 845f34c5-1b4a-4c94-8c24-cca8ec4ddcbe
    type: playbook
    task:
      id: 845f34c5-1b4a-4c94-8c24-cca8ec4ddcbe
      version: -1
      name: Get File Sample From Path - Generic V2
      description: |
        This playbook returns a file sample correlating to a path into the war-room using the following sub-playbooks:
        inputs:
        1) Get File Sample From Path - D2.
        2) Get File Sample From Path - VMware Carbon Black EDR (Live Response API).
      playbookName: Get File Sample From Path - Generic V2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Hostname:
        complex:
          root: inputs.Hostname
      Path:
        complex:
          root: inputs.Path
      Sensor_ID:
        complex:
          root: inputs.Sensor ID
      UseD2:
        complex:
          root: inputs.UseD2
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 35,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 850,
        "x": 35,
        "y": 50
      }
    }
  }
inputs:
- key: MD5
  value: {}
  required: false
  description: Get file sample from MD5 input.
  playbookInputQuery:
- key: SHA256
  value: {}
  required: false
  description: Get file sample from SHA256 input.
  playbookInputQuery:
- key: Hostname
  value: {}
  required: false
  description: Hostname of the machine on which the file is located.
  playbookInputQuery:
- key: Path
  value: {}
  required: false
  description: File path.
  playbookInputQuery:
- key: UseD2
  value: {}
  required: false
  description: |-
    Determines whether a D2 agent will be used to retrieve the file.
    Default is no.
  playbookInputQuery:
- key: Sensor ID
  value: {}
  required: false
  description: The sensor ID. Provided the sensor ID to run the command with a new
    session. The session will be created and closed automatically.
  playbookInputQuery:
outputs:
- contextPath: File
  description: File sample object
  type: unknown
- contextPath: CbLiveResponse.File.Size
  description: File size.
- contextPath: CbLiveResponse.File.SHA1
  description: File SHA1.
- contextPath: CbLiveResponse.File.SHA256
  description: File SHA256.
- contextPath: CbLiveResponse.File.Name
  description: File name.
- contextPath: CbLiveResponse.File.SSDeep
  description: File SSDeep.
- contextPath: CbLiveResponse.File.EntryID
  description: File EntryID.
- contextPath: CbLiveResponse.File.Info
  description: File info.
- contextPath: CbLiveResponse.File.Type
  description: File type.
- contextPath: CbLiveResponse.File.MD5
  description: File MD5.
- contextPath: CbLiveResponse.File.Extension
  description: File extension.
- contextPath: File.SHA256
  description: SHA256 hash of the file.
- contextPath: File.Name
  description: File name.
- contextPath: File.Size
  description: File size.
- contextPath: File.Safelisted
  description: Whether the file is on the Safe List.
- contextPath: File.Timestamp
  description: Timestamp.
- contextPath: File.MD5
  description: MD5 hash of the file.
- contextPath: File.Company
  description: Name of the company that released a binary.
- contextPath: File.OS
  description: The OS.
- contextPath: File.ProductName
  description: The product name.
- contextPath: File.Path
  description: The binary path.
- contextPath: File.LastSeen
  description: LThe lst time the binary was seen.
- contextPath: File.Description
  description: The binary description.
- contextPath: File.Hostname
  description: The binary hostname.
- contextPath: File.Extension
  description: The binary extension.
- contextPath: File.ServerAddedTimestamp
  description: The timestamp when the server was added.
- contextPath: File.InternalName
  description: The internal name.
sourceplaybookid: Retrieve File from Endpoint - Generic
fromversion: 5.0.0
tests:
- Retrieve File from Endpoint - Generic V2 Test

