id: Get File Sample By Hash - Generic v3
version: -1
name: Get File Sample By Hash - Generic v3
description: |-
  This playbook returns a file sample correlating to a hash in the war-room using the following sub-playbooks:
  - Get binary file by MD5 hash from Carbon Black telemetry data. - VMware Carbon Black EDR v2.
  - Get the threat (file) attached to a specific SHA256 hash- Cylance Protect v2.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e1c3bf5a-d7ba-4062-8877-ad2799d1db03
    type: start
    task:
      id: e1c3bf5a-d7ba-4062-8877-ad2799d1db03
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "5"
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: b5e5705d-8e32-41bb-8c3b-63c78bd2d14f
    type: title
    task:
      id: b5e5705d-8e32-41bb-8c3b-63c78bd2d14f
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a88a3bd6-0201-4203-8e8b-b3962ed19718
    type: playbook
    task:
      id: a88a3bd6-0201-4203-8e8b-b3962ed19718
      version: -1
      name: Get File Sample By Hash - Cylance Protect v2
      description: This playbook returns a file sample to the war-room given the file's
        SHA256 hash, using Cylance Protect v2 integration.
      playbookName: Get File Sample By Hash - Cylance Protect v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      SHA256:
        simple: ${inputs.SHA256}
      unzip: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 490,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "6":
    id: "6"
    taskid: ae94bf0f-480b-4cc7-8cb1-d44313763369
    type: playbook
    task:
      id: ae94bf0f-480b-4cc7-8cb1-d44313763369
      version: -1
      name: Get binary file from Carbon Black by MD5 hash
      description: 'This playbook retrieve binary file by MD5 hash from Carbon Black
        telemetry data.   '
      playbookName: Get binary file from Carbon Black by MD5 hash
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      MD5:
        complex:
          root: inputs.MD5
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 35,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 835,
        "x": 35,
        "y": 50
      }
    }
  }
inputs:
- key: MD5
  value: {}
  required: false
  description: Get file sample from MD5 input
  playbookInputQuery:
- key: SHA256
  value: {}
  required: false
  description: Get file sample from SHA256 input
  playbookInputQuery:
outputs:
- contextPath: File
  description: File sample object
  type: unknown
- contextPath: File.SHA256
  description: SHA256 hash of the file.
- contextPath: File.Name
  description: File name.
- contextPath: File.Size
  description: File size.
- contextPath: File.Safelisted
  description: Whether the file is on the Safe List.
- contextPath: File.Timestamp
  description: Timestamp.
- contextPath: File.MD5
  description: MD5 hash of the file.
- contextPath: File.Company
  description: Name of the company that released a binary.
- contextPath: File.OS
  description: The OS.
- contextPath: File.ProductName
  description: The product name.
- contextPath: File.Path
  description: The binary path.
- contextPath: File.LastSeen
  description: LThe lst time the binary was seen.
- contextPath: File.Description
  description: The binary description.
- contextPath: File.Hostname
  description: The binary hostname.
- contextPath: File.Extension
  description: The binary extension.
- contextPath: File.ServerAddedTimestamp
  description: The timestamp when the server was added.
- contextPath: File.InternalName
  description: The internal name.
sourceplaybookid: Get File Sample By Hash - Generic v2
tests:
- Account Enrichment - Generic v2.1 - Test
- Calculate Severity - Generic v2 - Test
- Calculate Severity - Standard - Test
- Test Convert file hash to corresponding hashes
- Dedup - Generic v2 - Test
- Detonate File - Generic Test
- Detonate File - No Files test
- Detonate URL - Generic Test
- Domain Enrichment - Generic v2 - Test
- Email Address Enrichment - Generic v2.1 - Test
- Endpoint Enrichment - Generic v2.1 - Test
- Extract Indicators From File - Generic v2 - Test
- Field polling test
- File Enrichment - Generic v2 - Test
- IP Enrichment - Generic v2 - Test
- Send Investigation Summary Reports - Test
- test-domain-indicator
- URL Enrichment - Generic v2 - Test
- Wait Until Datetime - Test
fromversion: 5.0.0
