contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: |-
  This playbook is intended to be used to secure Prisma Access customers.
  It automates the response to a Palo Alto Networks Firewall Threat log coming from the Cortex Data Lake. The domain in the threat is  enriched and if the security profile on the firewall is set to action "alert", the analyst will be provided with threat information and prompted whether to move the action to "block" on the firewall, which the playbook will automate if the analyst chooses to proceed. In parallel, the playbook checks the number of threats from the customer's source IP. If there have been more than 5  threats detected, the playbook will email the account team suggesting that the customer might need help enhancing their endpoint security and overall security posture. The threshold of 5 is configurable as a playbook input.
id: Prisma Access Threat Response
inputs:
- description: Number of incidents originating from a single source IP that would
    cause escalation of that source IP to the customer account owner.
  key: SourceIPIncidentCountThreshold
  playbookInputQuery:
  required: true
  value:
    simple: "5"
- description: Email address to notify when a customer's source IP generates more
    threats than the threshold above.
  key: AccountTeamEmail
  playbookInputQuery:
  required: false
  value: {}
name: Prisma Access Threat Response
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "23"
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7de51952-0933-4b9c-8bf1-b9bd0a1e887d
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 7de51952-0933-4b9c-8bf1-b9bd0a1e887d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 180,
          "y": 500
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: a60f4986-ffa3-495e-8cb2-4e33c955c8a9
      iscommand: true
      name: Close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: a60f4986-ffa3-495e-8cb2-4e33c955c8a9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 0,
          "y": 2760
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: ${incident.labels.file_name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: A context script for Domain entities
      id: e3658aea-fbba-4348-8fbf-3902f92a15a7
      iscommand: false
      name: DomainReputation
      script: DomainReputation
      tags:
      - enrichment
      type: regular
      version: -1
    taskid: e3658aea-fbba-4348-8fbf-3902f92a15a7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 280,
          "y": 1230
        }
      }
  "10":
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: 'Based on reviewing your configuration, we see the security profiles
            are only configured for visibility. Would you like to enhance security
            and apply a strict profile ? '
        options:
        - "Yes"
        - "No"
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      sender: ""
      title: SOC - Threat Identified
      totalanswers: 0
    id: "10"
    ignoreworker: false
    message:
      bcc:
      body:
        simple: "We identified a threat in your environment. <br/>\n*******************************************\
          \ <br/>\n\n\nDomain in Question : ${AutoFocus.Domain.IndicatorValue} <br/>\n\
          Verdicts: ${AutoFocus.Domain.LatestPanVerdicts.WF_SAMPLE} <br/>\nMalware\
          \ Family : ${AutoFocus.Domain.Tags.[0].TagName} <br/>\nDescription Of Malware\
          \ Family: ${AutoFocus.Domain.Tags.[0].Description} <br/>\n\nPlease click\
          \ link below for automated prevention. "
      cc:
      format: ""
      methods:
      - email
      subject:
        simple: 'SOC - Threat Identified '
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
        simple: ${IncidentOwner.email}
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a86c493e-e9c6-43fc-8757-1a6fe69eba45
      iscommand: false
      name: Send Enriched Data
      type: collection
      version: -1
    taskid: a86c493e-e9c6-43fc-8757-1a6fe69eba45
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1980
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            value:
              simple: SOC - Threat Identified .Answers.0
          operator: isExists
      label: "yes"
    id: "11"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4df059f8-09c7-40e5-8bc3-139d1fd60098
      iscommand: false
      name: EnhanceSecurity?
      type: condition
      version: -1
    taskid: 4df059f8-09c7-40e5-8bc3-139d1fd60098
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 2150
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: set
      category: {}
      cmd: {}
      command: {}
      dst: {}
      element:
        simple: |-
          <entry name="${incident.labels.rule_matched}">
              <profile-setting>
                <group>
                  <member>default-block</member>
                </group>
              </profile-setting>
             </entry>
      from: {}
      job-id: {}
      key: {}
      log-type: {}
      pcap-id: {}
      period: {}
      query: {}
      reportname: {}
      reporttype: {}
      search-time: {}
      serialno: {}
      target: {}
      to: {}
      type:
        simple: config
      using:
        simple: Paloalto-Fw
      where: {}
      xpath:
        simple: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Run any command supported in the API.
      id: 58918ccc-9d80-4736-8bc8-a502eec0dc63
      iscommand: true
      name: enhance-security
      script: Panorama|||panorama
      type: regular
      version: -1
    taskid: 58918ccc-9d80-4736-8bc8-a502eec0dc63
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 2450
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: Paloalto-Fw
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Commits a configuration to Palo Alto Firewall or Panorama, but
        does not validate if the commit was successful. Committing to Panorama does
        not push the configuration to the Firewalls. To push the configuration, run
        the panorama-push-to-device-group command.
      id: 75036120-8d41-47e8-8277-53b9f43a3532
      iscommand: true
      name: commit to firewall
      script: Panorama|||panorama-commit
      type: regular
      version: -1
    taskid: 75036120-8d41-47e8-8277-53b9f43a3532
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 2590
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${incident.labels.file_name}
          operator: isNotEmpty
      label: "yes"
    id: "16"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f5b7b001-19b2-4f19-8d49-f7f5a1e46e7c
      iscommand: false
      name: Domain in alert?
      type: condition
      version: -1
    taskid: f5b7b001-19b2-4f19-8d49-f7f5a1e46e7c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 180,
          "y": 880
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6a35548a-2e77-4cd3-8d27-9b483c12513f
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 6a35548a-2e77-4cd3-8d27-9b483c12513f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 0,
          "y": 2940
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d1bb293d-f39d-467b-82fc-8c6d7454e5d0
      iscommand: false
      name: Enrich Threat
      type: title
      version: -1
      description: ''
    taskid: d1bb293d-f39d-467b-82fc-8c6d7454e5d0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 180,
          "y": 700
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      end: {}
      query:
        simple: ${incident.labels.file_name}
      start: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieves the passive DNS results from active account sources.
      id: a2c6bb61-bd46-49d3-8759-2eb1fa85e09c
      iscommand: true
      name: PassiveTotal - Enrich with Passive DNS Information
      script: '|||pt-get-pdns-details'
      tags:
      - enrichment
      type: regular
      version: -1
    taskid: a2c6bb61-bd46-49d3-8759-2eb1fa85e09c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 1230
        }
      }
  "20":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: action
                root: incident.labels
          operator: containsString
          right:
            value:
              simple: '"alert"'
      label: "yes"
    id: "20"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1250fb51-1e7c-438f-895b-27e3f61d52b6
      iscommand: false
      name: Security Profile set to Alert?
      type: condition
      version: -1
    taskid: 1250fb51-1e7c-438f-895b-27e3f61d52b6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 0,
          "y": 1500
        }
      }
  "21":
    id: "21"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3573005e-abf8-4dab-8599-c1fbe598e257
      iscommand: false
      name: Enhance Security Profile
      type: title
      version: -1
      description: ''
    taskid: 3573005e-abf8-4dab-8599-c1fbe598e257
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1680
        }
      }
  "22":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: incidentIDs
                root: IncidentsWithIndicator
                transformers:
                - operator: count
          operator: greaterThanOrEqual
          right:
            iscontext: true
            value:
              simple: inputs.SourceIPIncidentCountThreshold
      label: "yes"
    id: "22"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8de94b77-d1fd-473a-8610-74c4895c85ff
      iscommand: false
      name: Is the number of incidents from this source IP over the threshold?
      type: condition
      version: -1
    taskid: 8de94b77-d1fd-473a-8610-74c4895c85ff
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -400,
          "y": 1060
        }
      }
  "23":
    id: "23"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 364e9a08-fb59-4b38-8ac0-411b9a24f9c2
      iscommand: false
      name: Account Escalation
      type: title
      version: -1
      description: ''
    taskid: 364e9a08-fb59-4b38-8ac0-411b9a24f9c2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -400,
          "y": 700
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1ab30981-5988-4356-8f4a-8347b45b3279
      iscommand: false
      name: Domain Enrichment
      type: title
      version: -1
      description: ''
    taskid: 1ab30981-5988-4356-8f4a-8347b45b3279
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 540,
          "y": 1060
        }
      }
  "25":
    id: "25"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        complex:
          accessor: source_ip
          root: incident.labels
          transformers:
          - operator: ParseJSON
          - args:
              field:
                value:
                  simple: value
            operator: getField
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Lookup incidents with specified indicator. Use currentIncidentId
        to omit the existing incident from output
      id: 77e0fb8f-e76c-4eb8-8d6d-129739c80839
      iscommand: false
      name: Get number of related incidents for this source IP
      script: findIncidentsWithIndicator
      type: regular
      version: -1
    taskid: 77e0fb8f-e76c-4eb8-8d6d-129739c80839
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -400,
          "y": 850
        }
      }
  "26":
    id: "26"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      additionalHeader: {}
      attachCIDs: {}
      attachIDs: {}
      attachNames: {}
      bcc: {}
      body: {}
      cc: {}
      htmlBody: {}
      raw_message: {}
      replyTo: {}
      subject:
        complex:
          accessor: source_ip
          root: incident.labels
          transformers:
          - operator: ParseJSON
          - args:
              field:
                value:
                  simple: value
            operator: getField
          - args:
              prefix:
                value:
                  simple: Multiple threats from customer IP [
              suffix:
                value:
                  simple: ']'
            operator: concat
      templateParams: {}
      to:
        simple: ${inputs.AccountTeamEmail}
      transientFile: {}
      transientFileCID: {}
      transientFileContent: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send an email
      id: 83e78130-163b-4c2a-8d77-f6eebe2716e3
      iscommand: true
      name: Email - Notify account owner of multiple threats from this customer's
        source  IP
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: 83e78130-163b-4c2a-8d77-f6eebe2716e3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -610,
          "y": 1745
        }
      }
  "27":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.AccountTeamEmail
          operator: isNotEmpty
      label: "yes"
    id: "27"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d2809876-75a1-4b13-8e95-eeef2a24ea77
      iscommand: false
      name: Is the Account Team Email configured?
      type: condition
      version: -1
    taskid: d2809876-75a1-4b13-8e95-eeef2a24ea77
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -610,
          "y": 1350
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Expose the incident owner into IncidentOwner context key
      id: eb65bbee-e453-47c0-87c6-f5d13a65a736
      iscommand: false
      name: Get information for incident owner
      script: ExposeIncidentOwner
      type: regular
      version: -1
    taskid: eb65bbee-e453-47c0-87c6-f5d13a65a736
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1815
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_2_#default#": 0.16,
      "20_2_#default#": 0.1,
      "22_2_#default#": 0.1,
      "27_2_#default#": 0.13
    },
    "paper": {
      "dimensions": {
        "height": 2505,
        "width": 1830,
        "x": -610,
        "y": 500
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
