id: Cortex XDR endpoints health check test
inputs: []
name: Cortex XDR endpoints health check test
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: adb31146-1451-4a71-89d9-a3cdd69cddaa
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: adb31146-1451-4a71-89d9-a3cdd69cddaa
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Email: {}
      LastSeenEndDate:
        simple: "2020-07-20"
      LastSeenStartDate:
        simple: "2020-07-20"
      MessageBody:
        simple: |-
          This message contains an automatically generated report by Cortex XSOAR, including a list of unhealthy and disconnected Cortex XDR endpoints.
          Please investigate and remediate according to the organisation's policy.
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        This playbook will query disconnected/lost Cortex XDR endpoints with a provided last seen time range playbook input.
        The playbook will also generate a CSV report, including a detailed list of the unhealthy endpoints, and send the report to the provided email addresses.
        This playbook also includes an incident type with a dedicated layout to visualize the collected data.
      id: 58fa242a-09de-4f9e-87a8-07f97c62b58d
      iscommand: false
      name: Cortex XDR endpoints health check
      playbookId: Cortex XDR endpoints health check
      type: playbook
      version: -1
    taskid: 58fa242a-09de-4f9e-87a8-07f97c62b58d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 35998676-daa9-4ee1-847d-88d68d065943
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 35998676-daa9-4ee1-847d-88d68d065943
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }

fromversion: 5.5.0
description: Test playbook for XDR endpoint health check
